Support running tests locally
When running the tests locally (e.g. during Debian package build), the
binary `salt-factories` is not available in the search path yet.
Therefore `test_salt_factories_cli` will fail:

```
FileNotFoundError: [Errno 2] No such file or directory: 'salt-factories'
```

So skip the test case if the binary cannot be found.

Signed-off-by: Benjamin Drung <benjamin.drung@ionos.com>