Finally made the event listener error proofed.
Some salt event messages apparently can't be decoded by msgpack, which
is weird, namely a job event message from salt virt module:
```
Traceback (most recent call last):
  File ".nox/pytest-parametrized-3-7-crypto-none-transport-zeromq-coverage-false/lib/python3.7/site-packages/saltfactories/plugins/event_listener.py", line 59, in _run
    decoded = msgpack.loads(payload, **msgpack_kwargs)
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: int is not allowed for map key
```
Anyway, we now handle that and keep the event listener running.
On top of that, we were't properly checking the stop sentinel, which is
now also fixed.